# -*- coding: utf-8 -*-
"""ambil data TA yang digunakan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x9-AaHsrjeViAAkUhfWFPvm_310cL1hC
"""

# ============================================================
# 1. Mount Google Drive
# ============================================================
from google.colab import drive
drive.mount('/content/drive')

# ============================================================
# 2. Import library yang dibutuhkan
# ============================================================
import os
import shutil
import pandas as pd

# ============================================================
# 3. Path ke file & folder KADID-10k (Sesuai yang kamu berikan)
# ============================================================
DMOS_PATH = "/content/drive/MyDrive/kadid10k/kadid10k/dmos.csv"
IMG_DIR   = "/content/drive/MyDrive/kadid10k/kadid10k/images"

# Folder output untuk sampel 30 gambar per kategori
OUT_DIR   = "/content/drive/MyDrive/kadid10k/kadid10k/samples_30_per_class"

# ============================================================
# 4. Baca file dmos.csv
# ============================================================
df = pd.read_csv(DMOS_PATH)

print("Kolom yang tersedia di dmos.csv:")
print(df.columns)
print(df.head())

# ------------------------------------------------------------
# Penting: SESUAIKAN nama kolom di bawah ini dengan kolom asli
# ------------------------------------------------------------
# Untuk KADID-10k biasanya:
# - nama file ada di kolom 'dist_img'
# - nilai kualitas ada di kolom 'dmos'
FILE_COL = "dist_img"   # ganti kalau namanya berbeda
DMOS_COL = "dmos"       # ganti kalau namanya berbeda

# Cek apakah kolom ada
if FILE_COL not in df.columns:
    raise ValueError(f"Kolom nama file '{FILE_COL}' tidak ditemukan di dmos.csv. Cek df.columns dan sesuaikan.")

if DMOS_COL not in df.columns:
    raise ValueError(f"Kolom DMOS '{DMOS_COL}' tidak ditemukan di dmos.csv. Cek df.columns dan sesuaikan.")

# Pastikan kolom DMOS bertipe numerik
df[DMOS_COL] = pd.to_numeric(df[DMOS_COL], errors="coerce")

# Drop baris yang DMOS-nya NaN (kalau ada)
df = df.dropna(subset=[DMOS_COL]).reset_index(drop=True)

print("\nJumlah total data setelah bersih:", len(df))

# ============================================================
# 5. Buat kategori kualitas berdasarkan nilai DMOS
#    (semakin besar DMOS = kualitas lebih tinggi)
#    Strategi: pakai kuantil 1/3 dan 2/3
# ============================================================
q1 = df[DMOS_COL].quantile(1/3)
q2 = df[DMOS_COL].quantile(2/3)

print("\nBatas kuantil:")
print("q1 (batas low/medium)  :", q1)
print("q2 (batas medium/high) :", q2)

def label_quality(score, q1, q2):
    if score <= q1:
        return "low"
    elif score <= q2:
        return "medium"
    else:
        return "high"

df["quality"] = df[DMOS_COL].apply(lambda x: label_quality(x, q1, q2))

print("\nDistribusi kelas kualitas:")
print(df["quality"].value_counts())

# ============================================================
# 6. Sampling 30 gambar dari tiap kategori
# ============================================================
n_sample = 30
samples = {}

for q in ["low", "medium", "high"]:
    subset = df[df["quality"] == q]
    if len(subset) < n_sample:
        print(f"[WARNING] Kelas '{q}' hanya punya {len(subset)} sampel. "
              f"Maka diambil semua ({len(subset)}).")
        samples[q] = subset
    else:
        samples[q] = subset.sample(n_sample, random_state=42)

# Gabungkan metadata sampel
selected_df = pd.concat(samples.values(), axis=0).reset_index(drop=True)

print("\nJumlah sampel per kelas yang dipilih:")
print(selected_df["quality"].value_counts())

# ============================================================
# 7. Buat folder output & copy file gambar sesuai kategori
# ============================================================
os.makedirs(OUT_DIR, exist_ok=True)

for q in ["low", "medium", "high"]:
    class_dir = os.path.join(OUT_DIR, q)
    os.makedirs(class_dir, exist_ok=True)

missing_files = []

for _, row in selected_df.iterrows():
    fname = row[FILE_COL]
    qcls  = row["quality"]

    src = os.path.join(IMG_DIR, fname)
    dst = os.path.join(OUT_DIR, qcls, fname)

    if os.path.exists(src):
        shutil.copy2(src, dst)
    else:
        print(f"[MISSING] File tidak ditemukan: {src}")
        missing_files.append(fname)

# ============================================================
# 8. Simpan metadata sampel yang dipilih
# ============================================================
meta_path = os.path.join(OUT_DIR, "selected_metadata.csv")
selected_df.to_csv(meta_path, index=False)

print("\n=== SELESAI ===")
print(f"Folder output   : {OUT_DIR}")
print(f"Metadata tersimpan di: {meta_path}")
if missing_files:
    print(f"Ada {len(missing_files)} file yang hilang (lihat log di atas).")
else:
    print("Semua file sampel berhasil dicopy.")

